# vcs:
#   uri: https://github.com/alpha-hack-program/yolo-uno-cards.git
#   ref: main
#   name: alpha-hack-program/yolo-uno-cards

gitSslVerify: true

dataScienceProjectDisplayName: yolo
dataScienceProjectNamespace: yolo

instanceName: yolo
partOf: yolo

createNamespace: true

kfpUpsertTektonPipelineName: kfp-upsert-pl

pipelinesWorkspaceDefaultSize: 2Gi

pipelinesServiceAccountName: build-bot-sa

eventListenerServiceAccountName: pipeline

rhoaiModelRegistriesNamespace: rhoai-model-registries

pipelines:
  enabled: true
  connection:
    name: pipelines
    displayName: Pipelines S3 Storage
    description: S3-compatible storage connection for ML pipelines
    type: s3
    typeProtocol: s3
    typeRef: s3
    scheme: http
    host: minio.ic-shared-minio.svc
    port: "9000"
    awsAccessKeyId: minio
    awsSecretAccessKey: minio123
    awsDefaultRegion: none
    awsS3Bucket: pipelines

# S3 configuration for the s3-job.yaml template
s3:
  config:
    awsS3BucketList: pipelines,models,datasets
  connection:
    awsAccessKeyId: minio
    awsSecretAccessKey: minio123
    awsS3Endpoint: http://minio.ic-shared-minio.svc:9000

pythonImage:
  version: "3.9"
  name: "python"
  tag: "3.9-ubi8"

images:
  python3: "registry.redhat.io/ubi8/python-39:1-158"

mountCaCerts: "false"

setup:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
