# PIPELINE DEFINITION
# Name: train-model-optuna
# Inputs:
#    author: str
#    experiment_name_prefix: str
#    images_dataset_name: str
#    images_dataset_pvc_name: str
#    images_dataset_pvc_size_in_gi: int
#    images_dataset_yaml: str
#    images_datasets_root_folder: str
#    istio_system_namespace: str
#    model_name: str
#    model_registry_name: str
#    model_tags: str
#    models_root_folder: str
#    n_trials: int
#    owner: str
#    pipeline_name: str
#    search_space: str
# Outputs:
#    results_output_metrics: system.Metrics
#    train-model-optuna-results_output_metrics: system.Metrics
components:
  comp-train-model-optuna:
    executorLabel: exec-train-model-optuna
    inputDefinitions:
      parameters:
        author:
          parameterType: STRING
        experiment_name_prefix:
          parameterType: STRING
        images_dataset_name:
          parameterType: STRING
        images_dataset_pvc_name:
          parameterType: STRING
        images_dataset_pvc_size_in_gi:
          parameterType: NUMBER_INTEGER
        images_dataset_yaml:
          parameterType: STRING
        images_datasets_root_folder:
          parameterType: STRING
        istio_system_namespace:
          parameterType: STRING
        model_name:
          parameterType: STRING
        model_registry_name:
          parameterType: STRING
        model_tags:
          parameterType: STRING
        models_root_folder:
          parameterType: STRING
        n_trials:
          parameterType: NUMBER_INTEGER
        owner:
          parameterType: STRING
        pipeline_name:
          parameterType: STRING
        search_space:
          parameterType: STRING
    outputDefinitions:
      artifacts:
        results_output_metrics:
          artifactType:
            schemaTitle: system.Metrics
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-train-model-optuna:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - train_model_optuna
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'load_dotenv==0.1.0'\
          \ 'optuna==4.1.0' 'kfp[kubernetes]==2.8.0' 'kubernetes==23.6.0' && \"$0\"\
          \ \"$@\"\n"
        - python3
        - -m
        - kfp.dsl.executor_main
        image: quay.io/atarazana/train_yolo_optuna:latest
pipelineInfo:
  name: train-model-optuna
root:
  dag:
    outputs:
      artifacts:
        results_output_metrics:
          artifactSelectors:
          - outputArtifactKey: results_output_metrics
            producerSubtask: train-model-optuna
        train-model-optuna-results_output_metrics:
          artifactSelectors:
          - outputArtifactKey: results_output_metrics
            producerSubtask: train-model-optuna
    tasks:
      train-model-optuna:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-train-model-optuna
        inputs:
          parameters:
            author:
              componentInputParameter: author
            experiment_name_prefix:
              componentInputParameter: experiment_name_prefix
            images_dataset_name:
              componentInputParameter: images_dataset_name
            images_dataset_pvc_name:
              componentInputParameter: images_dataset_pvc_name
            images_dataset_pvc_size_in_gi:
              componentInputParameter: images_dataset_pvc_size_in_gi
            images_dataset_yaml:
              componentInputParameter: images_dataset_yaml
            images_datasets_root_folder:
              componentInputParameter: images_datasets_root_folder
            istio_system_namespace:
              componentInputParameter: istio_system_namespace
            model_name:
              componentInputParameter: model_name
            model_registry_name:
              componentInputParameter: model_registry_name
            model_tags:
              componentInputParameter: model_tags
            models_root_folder:
              componentInputParameter: models_root_folder
            n_trials:
              componentInputParameter: n_trials
            owner:
              componentInputParameter: owner
            pipeline_name:
              componentInputParameter: pipeline_name
            search_space:
              componentInputParameter: search_space
        taskInfo:
          name: train-model-optuna
  inputDefinitions:
    parameters:
      author:
        parameterType: STRING
      experiment_name_prefix:
        parameterType: STRING
      images_dataset_name:
        parameterType: STRING
      images_dataset_pvc_name:
        parameterType: STRING
      images_dataset_pvc_size_in_gi:
        parameterType: NUMBER_INTEGER
      images_dataset_yaml:
        parameterType: STRING
      images_datasets_root_folder:
        parameterType: STRING
      istio_system_namespace:
        parameterType: STRING
      model_name:
        parameterType: STRING
      model_registry_name:
        parameterType: STRING
      model_tags:
        parameterType: STRING
      models_root_folder:
        parameterType: STRING
      n_trials:
        parameterType: NUMBER_INTEGER
      owner:
        parameterType: STRING
      pipeline_name:
        parameterType: STRING
      search_space:
        parameterType: STRING
  outputDefinitions:
    artifacts:
      results_output_metrics:
        artifactType:
          schemaTitle: system.Metrics
          schemaVersion: 0.0.1
      train-model-optuna-results_output_metrics:
        artifactType:
          schemaTitle: system.Metrics
          schemaVersion: 0.0.1
schemaVersion: 2.1.0
sdkVersion: kfp-2.8.0
