{{- range .Values.modelRegistries }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.argocdNamespace }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ $.Values.modelRegistriesApplication.registry.namespace | default "rhoai-model-registries" }}
  source:
    path: {{ $.Values.modelRegistriesApplication.path }}
    repoURL: {{ $.Values.modelRegistriesApplication.repoURL }}
    targetRevision: {{ $.Values.modelRegistriesApplication.targetRevision | default "main" }}
    helm:
      values: |
        registry:
          namespace: {{ $.Values.modelRegistriesApplication.registry.namespace | default "rhoai-model-registries" }}
          grpc:
            port: {{ $.Values.modelRegistriesApplication.registry.grpc.port | default 9090 }}
            {{- with $.Values.modelRegistriesApplication.registry.grpc.image }}
            image: {{ . }}
            {{- end }}
            {{- with $.Values.modelRegistriesApplication.registry.grpc.resources }}
            resources:
              limits:
                cpu: {{ .limits.cpu | default "100m" }}
                memory: {{ .limits.memory | default "256Mi" }}
              requests:
                cpu: {{ .requests.cpu | default "100m" }}
                memory: {{ .requests.memory | default "256Mi" }}
            {{- end }}
          rest:
            port: {{ $.Values.modelRegistriesApplication.registry.rest.port | default 8080 }}
            serviceRoute: {{ .serviceRoute | default $.Values.modelRegistriesApplication.registry.rest.serviceRoute | default "disabled" }}
            {{- with $.Values.modelRegistriesApplication.registry.rest.image }}
            image: {{ . }}
            {{- end }}
            {{- with $.Values.modelRegistriesApplication.registry.rest.resources }}
            resources:
              limits:
                cpu: {{ .limits.cpu | default "100m" }}
                memory: {{ .limits.memory | default "256Mi" }}
              requests:
                cpu: {{ .requests.cpu | default "100m" }}
                memory: {{ .requests.memory | default "256Mi" }}
            {{- end }}
        registryDb:
          databaseName: {{ .databaseName | default "metadb" }}
          databaseUser: {{ .databaseUser | default "root" }}
          databasePassword: {{ .databasePassword }}
        {{- with $.Values.modelRegistriesApplication.pvc }}
        pvc:
          {{- with .metadataMysql }}
          metadataMysql:
            storageRequest: {{ .storageRequest | default "10Gi" }}
          {{- end }}
        {{- end }}
        {{- with $.Values.modelRegistriesApplication.registryDb }}
        registryDb:
          {{- with .allowEmptyPassword }}
          allowEmptyPassword: {{ . | quote }}
          {{- end }}
          {{- with .dbContainer }}
          dbContainer:
            {{- with .image }}
            image:
              repository: {{ .repository | default "mysql" }}
              tag: {{ .tag | default "8.0.3" | quote }}
            {{- end }}
            {{- with .imagePullPolicy }}
            imagePullPolicy: {{ . }}
            {{- end }}
          {{- end }}
          {{- with .replicas }}
          replicas: {{ . }}
          {{- end }}
          {{- with .revisionHistoryLimit }}
          revisionHistoryLimit: {{ . }}
          {{- end }}
          {{- with .strategy }}
          strategy:
            type: {{ .type | default "Recreate" }}
          {{- end }}
          {{- with .type }}
          type: {{ . }}
          {{- end }}
        {{- end }}
  syncPolicy:
    automated:
      selfHeal: true
{{- end }}