---
{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    openshift.io/description: "{{ .Values.namespace }}"
    openshift.io/display-name: '{{ .Values.namespace }}'
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops #argocd instance ns
    kubernetes.io/metadata.name: "{{ .Values.namespace }}"
    modelmesh-enabled: 'false'
    opendatahub.io/dashboard: 'true'
{{- end }}