apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.instanceName }}-pipelines
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.argocdNamespace }}
  source:
    path: gitops/pipelines
    repoURL: {{ .Values.vcs.uri }}
    targetRevision: {{ .Values.vcs.ref }}
    helm:
      parameters:
        - name: gitSslVerify
          value: "{{ .Values.gitSslVerify }}"
        - name: vcs.uri
          value: "{{ .Values.vcs.uri }}"
        - name: vcs.ref
          value: "{{ .Values.vcs.ref }}"
        - name: createNamespace
          value: "false" # This is set to false because the namespace is created by the yolo application
        - name: instanceName
          value: "{{ .Values.instanceName }}"
        - name: dataScienceProjectNamespace
          value: "{{ .Values.namespace }}"
        - name: dataScienceProjectDisplayName
          value: "{{ .Values.namespace }}"
        - name: mountCaCerts
          value: "{{ .Values.mountCaCerts }}"
        - name: pipelines.connection.name
          value: "{{ .Values.pipelines.connection.name }}"
        - name: pipelines.connection.displayName
          value: "{{ .Values.pipelines.connection.displayName }}"
        - name: pipelines.connection.type
          value: "{{ .Values.pipelines.connection.type }}"
        - name: pipelines.connection.scheme
          value: "{{ .Values.pipelines.connection.scheme }}"
        - name: pipelines.connection.awsAccessKeyId
          value: "{{ .Values.pipelines.connection.awsAccessKeyId }}"
        - name: pipelines.connection.awsSecretAccessKey
          value: "{{ .Values.pipelines.connection.awsSecretAccessKey }}"
        - name: pipelines.connection.awsDefaultRegion
          value: "{{ .Values.pipelines.connection.awsDefaultRegion }}"
        - name: pipelines.connection.awsS3Bucket
          value: "{{ .Values.pipelines.connection.awsS3Bucket }}"
        - name: pipelines.connection.awsS3Endpoint
          value: "{{ .Values.pipelines.connection.awsS3Endpoint }}"
  syncPolicy:
    automated:
      # prune: true
      selfHeal: true