# PIPELINE DEFINITION
# Name: pipeline
# Inputs:
#    batch_size: int [Default: 2.0]
#    confidence_threshold: float [Default: 0.001]
#    epochs: int [Default: 2.0]
#    experiment_name: str [Default: 'uno-cards-v1.2-0']
#    force_clean: bool [Default: False]
#    image_size: int [Default: 640.0]
#    images_dataset_name: str [Default: 'uno-cards-v1.2']
#    images_dataset_pvc_name: str [Default: 'images-datasets-pvc']
#    images_dataset_pvc_size_in_gi: int [Default: 5.0]
#    images_dataset_yaml: str [Default: 'data.yaml']
#    images_datasets_root_folder: str [Default: 'datasets']
#    iou_threshold: float [Default: 0.7]
#    label_smoothing: float [Default: 0.1]
#    learning_rate: float [Default: 0.001]
#    model_name: str [Default: 'yolov8n']
#    models_root_folder: str [Default: 'models']
#    momentum: float [Default: 0.937]
#    optimizer: str [Default: 'Adam']
#    run_name: str [Default: 'uno-cards']
#    tracking_uri: str [Default: 'http://mlflow-server:8080']
#    weight_decay: float [Default: 0.0005]
# Outputs:
#    train-yolo-results_output_metrics: system.Metrics
components:
  comp-train-yolo:
    executorLabel: exec-train-yolo
    inputDefinitions:
      parameters:
        batch_size:
          parameterType: NUMBER_INTEGER
        confidence_threshold:
          parameterType: NUMBER_DOUBLE
        epochs:
          parameterType: NUMBER_INTEGER
        experiment_name:
          parameterType: STRING
        image_size:
          parameterType: NUMBER_INTEGER
        images_dataset_name:
          parameterType: STRING
        images_dataset_yaml:
          parameterType: STRING
        images_datasets_root_folder:
          parameterType: STRING
        iou_threshold:
          parameterType: NUMBER_DOUBLE
        label_smoothing:
          parameterType: NUMBER_DOUBLE
        learning_rate:
          parameterType: NUMBER_DOUBLE
        model_name:
          parameterType: STRING
        models_root_folder:
          parameterType: STRING
        momentum:
          parameterType: NUMBER_DOUBLE
        optimizer:
          parameterType: STRING
        root_mount_path:
          parameterType: STRING
        run_name:
          parameterType: STRING
        tracking_uri:
          parameterType: STRING
        weight_decay:
          parameterType: NUMBER_DOUBLE
    outputDefinitions:
      artifacts:
        results_output_metrics:
          artifactType:
            schemaTitle: system.Metrics
            schemaVersion: 0.0.1
      parameters:
        metric_value_output:
          parameterType: NUMBER_DOUBLE
        model_name_output:
          parameterType: STRING
deploymentSpec:
  executors:
    exec-train-yolo:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - train_yolo
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'ultralytics==8.3.22'\
          \ 'load_dotenv==0.1.0' 'numpy==1.26.4' 'mlflow==2.17.1' 'onnxruntime==1.19.2'\
          \ 'onnxslim==0.1.36' && \"$0\" \"$@\"\n"
        - python3
        - -m
        - kfp.dsl.executor_main
        image: quay.io/atarazana/train_yolo:v1.0.1
pipelineInfo:
  name: pipeline
root:
  dag:
    outputs:
      artifacts:
        train-yolo-results_output_metrics:
          artifactSelectors:
          - outputArtifactKey: results_output_metrics
            producerSubtask: train-yolo
    tasks:
      train-yolo:
        cachingOptions: {}
        componentRef:
          name: comp-train-yolo
        inputs:
          parameters:
            batch_size:
              componentInputParameter: batch_size
            confidence_threshold:
              componentInputParameter: confidence_threshold
            epochs:
              componentInputParameter: epochs
            experiment_name:
              componentInputParameter: experiment_name
            image_size:
              componentInputParameter: image_size
            images_dataset_name:
              componentInputParameter: images_dataset_name
            images_dataset_yaml:
              componentInputParameter: images_dataset_yaml
            images_datasets_root_folder:
              componentInputParameter: images_datasets_root_folder
            iou_threshold:
              componentInputParameter: iou_threshold
            label_smoothing:
              componentInputParameter: label_smoothing
            learning_rate:
              componentInputParameter: learning_rate
            model_name:
              componentInputParameter: model_name
            models_root_folder:
              componentInputParameter: models_root_folder
            momentum:
              componentInputParameter: momentum
            optimizer:
              componentInputParameter: optimizer
            root_mount_path:
              runtimeValue:
                constant: /opt/app/src
            run_name:
              componentInputParameter: run_name
            tracking_uri:
              componentInputParameter: tracking_uri
            weight_decay:
              componentInputParameter: weight_decay
        taskInfo:
          name: train-yolo
  inputDefinitions:
    parameters:
      batch_size:
        defaultValue: 2.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      confidence_threshold:
        defaultValue: 0.001
        isOptional: true
        parameterType: NUMBER_DOUBLE
      epochs:
        defaultValue: 2.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      experiment_name:
        defaultValue: uno-cards-v1.2-0
        isOptional: true
        parameterType: STRING
      force_clean:
        defaultValue: false
        isOptional: true
        parameterType: BOOLEAN
      image_size:
        defaultValue: 640.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      images_dataset_name:
        defaultValue: uno-cards-v1.2
        isOptional: true
        parameterType: STRING
      images_dataset_pvc_name:
        defaultValue: images-datasets-pvc
        isOptional: true
        parameterType: STRING
      images_dataset_pvc_size_in_gi:
        defaultValue: 5.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      images_dataset_yaml:
        defaultValue: data.yaml
        isOptional: true
        parameterType: STRING
      images_datasets_root_folder:
        defaultValue: datasets
        isOptional: true
        parameterType: STRING
      iou_threshold:
        defaultValue: 0.7
        isOptional: true
        parameterType: NUMBER_DOUBLE
      label_smoothing:
        defaultValue: 0.1
        isOptional: true
        parameterType: NUMBER_DOUBLE
      learning_rate:
        defaultValue: 0.001
        isOptional: true
        parameterType: NUMBER_DOUBLE
      model_name:
        defaultValue: yolov8n
        isOptional: true
        parameterType: STRING
      models_root_folder:
        defaultValue: models
        isOptional: true
        parameterType: STRING
      momentum:
        defaultValue: 0.937
        isOptional: true
        parameterType: NUMBER_DOUBLE
      optimizer:
        defaultValue: Adam
        isOptional: true
        parameterType: STRING
      run_name:
        defaultValue: uno-cards
        isOptional: true
        parameterType: STRING
      tracking_uri:
        defaultValue: http://mlflow-server:8080
        isOptional: true
        parameterType: STRING
      weight_decay:
        defaultValue: 0.0005
        isOptional: true
        parameterType: NUMBER_DOUBLE
  outputDefinitions:
    artifacts:
      train-yolo-results_output_metrics:
        artifactType:
          schemaTitle: system.Metrics
          schemaVersion: 0.0.1
schemaVersion: 2.1.0
sdkVersion: kfp-2.8.0
