# Use an official Rust image as a builder
FROM rust:1.74 as builder

# Create app directory
WORKDIR /app

# Copy source code
COPY . .

# Build the application
RUN cargo build --release

# Use a smaller base image for the final container
FROM debian:bookworm-slim

# Copy the compiled binary from the builder
COPY --from=builder /app/target/release/rust_calc /usr/local/bin/rust_calc

# Define the entrypoint
ENTRYPOINT ["rust_calc"]
