---
# Give the pipeline-runner-dspa service account permissions to read routes in ns rhoai-model-registries
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.rhoaiModelRegistriesNamespace }}
  name: route-reader
rules:
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-runner-route-reader
  namespace: {{ .Values.rhoaiModelRegistriesNamespace }}
subjects:
- kind: ServiceAccount
  name: pipeline-runner-dspa
  namespace: {{ .Values.dataScienceProjectNamespace }}
roleRef:
  kind: Role
  name: route-reader
  apiGroup: rbac.authorization.k8s.io
---
# Give the pipeline-runner-dspa service account permissions to create PVCs in the data science project namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-manager-dspa
  namespace: {{ .Values.dataScienceProjectNamespace }}  
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "delete", "get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-manager-dspa
  namespace: {{ .Values.dataScienceProjectNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
- kind: ServiceAccount
  name: pipeline-runner-dspa
  namespace: {{ .Values.dataScienceProjectNamespace }}
roleRef:
  kind: Role
  name: storage-manager-dspa
  apiGroup: rbac.authorization.k8s.io
