# Give the pipeline-runner-dspa service account permissions to create PVCs
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-manager-dspa
  namespace: {{ .Values.dataScienceProjectNamespace }}  
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "delete", "get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-manager-dspa
  namespace: {{ .Values.dataScienceProjectNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
- kind: ServiceAccount
  name: pipeline-runner-dspa
  namespace: {{ .Values.dataScienceProjectNamespace }}
roleRef:
  kind: Role
  name: storage-manager-dspa
  apiGroup: rbac.authorization.k8s.io
